x-startup-wrapper:
  &startup-wrapper
    entrypoint: /startup-script/entrypoint.sh

services:
  # The license monitor with its health check
  license:
    build: ./license-monitor
    container_name: license
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.txt"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - startup-net

  # A PostgreSQL database for Superset metadata
  nginx:
    <<: *startup-wrapper
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./startup-script:/startup-script:ro
    networks:
      - startup-net
    depends_on:
      license:
        condition: service_healthy
    command: ["/docker-entrypoint.sh", "nginx", "-g", "daemon off;"]

networks:
  startup-net:
    driver: bridge